apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-master-config
data:
  master.cnf: |
    [mysqld]
    server-id=1
    log-bin=mysql-bin
    binlog_format=row
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-master
  labels:
    app: mysql-master
spec:
  ports:
  - port: 3306
  selector:
    app: mysql-master
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-master
spec:
  selector:
    matchLabels:
      app: mysql-master
  template:
    metadata:
      labels:
        app: mysql-master
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "rootpassword"
        - name: MYSQL_REPLICATION_USER
          value: "repl"
        - name: MYSQL_REPLICATION_PASSWORD
          value: "replpassword"
        volumeMounts:
        - name: config-volume
          mountPath: /etc/mysql/conf.d
        - name: log-volume
          mountPath: /var/log/mysql
      # Sidecar to simulate writing to retry log (for demonstration)
      - name: log-generator
        image: busybox
        command: ["/bin/sh", "-c"]
        args:
        - |
          mkdir -p /var/log/mysql
          while true; do
            echo "$(date) - Retry log entry" >> /var/log/mysql/retry.log
            sleep 5
          done
        volumeMounts:
        - name: log-volume
          mountPath: /var/log/mysql
      # Sidecar to ship logs
      - name: log-shipper
        image: python:3.9-slim
        command: ["/bin/sh", "-c"]
        args:
        - |
          pip install pika
          python /app/shipper.py
        env:
        - name: RABBITMQ_HOST
          value: "rabbitmq"
        volumeMounts:
        - name: log-volume
          mountPath: /var/log/mysql
        - name: shipper-config
          mountPath: /app/shipper.py
          subPath: shipper.py
      volumes:
      - name: config-volume
        configMap:
          name: mysql-master-config
      - name: log-volume
        emptyDir: {}
      - name: shipper-config
        configMap:
          name: log-shipper-config
